server:
  port: 8085
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
## 설정파일 (Properties)
#server.port = 8081
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
